// This file was generated by qlalr - DO NOT EDIT!
#ifndef GEDAELEMENTGRAMMAR_P_H
#define GEDAELEMENTGRAMMAR_P_H

class GedaElementGrammar
{
public:
  enum {
    EOF_SYMBOL = 0,
    ELEMENT = 1,
    ELEMENTARC = 6,
    ELEMENTLINE = 5,
    HEXNUMBER = 13,
    LEFTBRACKET = 9,
    LEFTPAREN = 7,
    MARK = 4,
    NUMBER = 11,
    PAD = 2,
    PIN = 3,
    RIGHTBRACKET = 10,
    RIGHTPAREN = 8,
    STRING = 12,

    ACCEPT_STATE = 179,
    RULE_COUNT = 98,
    STATE_COUNT = 180,
    TERMINAL_COUNT = 14,
    NON_TERMINAL_COUNT = 80,

    GOTO_INDEX_OFFSET = 180,
    GOTO_INFO_OFFSET = 73,
    GOTO_CHECK_OFFSET = 73
  };

  static const char  *const spell [];
  static const int            lhs [];
  static const int            rhs [];

#ifndef QLALR_NO_GEDAELEMENTGRAMMAR_DEBUG_INFO
  static const int     rule_index [];
  static const int      rule_info [];
#endif // QLALR_NO_GEDAELEMENTGRAMMAR_DEBUG_INFO

  static const int   goto_default [];
  static const int action_default [];
  static const int   action_index [];
  static const int    action_info [];
  static const int   action_check [];

  static inline int nt_action (int state, int nt)
  {
    const int *const goto_index = &action_index [GOTO_INDEX_OFFSET];
    const int *const goto_check = &action_check [GOTO_CHECK_OFFSET];

    const int yyn = goto_index [state] + nt;

    if (yyn < 0 || goto_check [yyn] != nt)
      return goto_default [nt];

    const int *const goto_info = &action_info [GOTO_INFO_OFFSET];
    return goto_info [yyn];
  }

  static inline int t_action (int state, int token)
  {
    const int yyn = action_index [state] + token;

    if (yyn < 0 || action_check [yyn] != token)
      return - action_default [state];

    return action_info [yyn];
  }
};


#endif // GEDAELEMENTGRAMMAR_P_H

